name = "COBS"
uuid = "51d40088-776c-571e-837e-515b83a6b6e6"
authors = ["yakir12 <12.yakir@gmail.com>"]
version = "0.0.1"

[deps]

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]

[compat]
julia = "^1"
